apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-dev
  labels:
    app: gcp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gcp
  template:
    metadata:
      labels:
        app: gcp
    spec:
      containers:
      - name: gcp-dev
        image: gcr.io/secret-fountain-384608/my-docker-repo/gcp-dev:latest
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          value: "5000"
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: gcp
    app.kubernetes.io/managed-by: gcp-cloud-build-deploy
  name: gcp-service
  namespace: gcpdev
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: gcp
  type: LoadBalancer
status:
  loadBalancer: {}
